### ISSUE TITLE
memory deallocation in libbwapy.c

### ISSUE THREAD

**Issue by vibansal** [nanoporetech/bwapy#13]
Thank you for sharing this very useful code. 

I have found that the function 'free_mem_aln_v' does not free memory allocated to alns->aln in the function 'new_mem_aln_v'. This causes a memory issue when calling the align_seq function repeatedly. Adding the line 'free(alns->aln)' to the function fixes this problem.

**Comment by cjw85** [comment]
I've added this line:
https://github.com/nanoporetech/bwapy/blob/master/bwapy/libbwapy.c#L87

Thanks!
