### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by rasto2211** [nanoporetech/bwapy#5]
Does this package work with python3? I'm getting this error:
```
AttributeError: type object 'Cython.Compiler.Scanning.Method' has no attribute '__reduce_cython__'
```
when I run:
```
python3 setup.py install --user
```

Any idea how to make it work for python3?

**Comment by cjw85** [comment]
Hi @rasto2211,

The Makefile illustrates the recommended way to install the package. Can you install the package using the Makefile? This will create a Python3 virtual environment and install the package into that?

I'm unsure why you are seeing errors from Cython, as the package does not require Cython. Is it possible that you have something amiss in your python3 environment or Cython installation? Installing into a virtual environment as above may provide some clues.

**Comment by rasto2211** [comment]
Ok, I was missing `cffi`. Now it works.
