### ISSUE TITLE
Any interest in a Bioconda package?

### ISSUE THREAD

**Issue by kyleabeauchamp** [nanoporetech/bwapy#9]

**Comment by cjw85** [comment]
This is not something we will be making. If we were to make installation simpler, I think we would push wheels to pypi. This doesn't of course mean someone else can't create a bioconda recipe from this project.

**Comment by kyleabeauchamp** [comment]
I've opened a PR on bioconda: https://github.com/bioconda/bioconda-recipes/pull/8507

I ended up grabbing master and calling it 0.1.4---is that versioning acceptable to you?

**Comment by cjw85** [comment]
I've created a [v0.1.4 tag](https://github.com/nanoporetech/bwapy/releases/tag/v0.1.4).

**Comment by kyleabeauchamp** [comment]
Thanks for the quick response!  Package is built and online: https://anaconda.org/bioconda/bwapy/files
